### ISSUE TITLE
Radio options are not validated clientside

### ISSUE THREAD

**Issue by asecondwill** [sheadawson/silverstripe-zenvalidator#15]
If i create a field:
````
 new OptionsetField('Contact', 'Please contact me via:', array(
              'Phone' => 'Phone',
              'Email' => 'Email'
          )),

````

and then require it:

````
$validator->addRequiredFields(array('FirstName', 'LastName', 'Contact', 'Phone', 'Email'  ));
````

Then it is required server side but not by parsley.  Possibly solve it by preselecting one of the options, although that might not be awesome UX. 

Sorry for all the tickets this week.

**Comment by lekoala** [comment]
hey @sheadawson I think we can close this :-)

**Comment by sheadawson** [comment]
Great. I love closing issues :)
