### ISSUE TITLE
CheckboxSetField not working

### ISSUE THREAD

**Issue by wandl** [sheadawson/silverstripe-zenvalidator#24]
Hi Shea,

I was having problems getting SS CheckboxSetField to validate as a group using parsley, I noticed you updated your module to parsley 2.0.6 and added a fix, so I promptly updated hoping to solve my issue, the problem is it seems that data-parsley-multiple expects the same value on each checkbox in the group? I noticed that after your fix my CheckboxSetField checkboxes are all set to data-parsley-multiple=Name1 data-parsley-multiple=Name2 data-parsley-multiple=Name3 etc..

Could you provide an example of using this do you need to use in conjunction with data-parsley-mincheck=1?

Even if I manually set my attributes on my CheckboxSetField (this is what I was doing before update) I still get no validation occurring

`$myFileld->setAttribute('data-parsley-multiple', 'my-group');`
`$myField->setAttribute('data-parsley-mincheck', 1);`

Any help much appreciated have been tearing my hair out over this.

PS. Nice module keep up the good work :)

**Comment by lekoala** [comment]
I think this issue was probably due to the custom template for CheckboxSetField not being use. @sheadawson do we close this?

**Comment by sheadawson** [comment]
Yeap!
