### ISSUE TITLE
Custom validators not used...

### ISSUE THREAD

**Issue by Martimiz** [sheadawson/silverstripe-zenvalidator#27]
First of all thanks again for a very sweet module :)

I wanted to use the default Upload_Validator for a FileField in collaboration with Zenvaldator, but that doesn't work. This seems to be easily fixed the same way as in the RequiredFields validator, by walking along the FormFields first:

	public function php($data){	
		$valid = true;

		$fields = $this->form->Fields();

		foreach($fields as $field) {
			$valid = ($field->validate($this) && $valid);
		}
		...

Do you see any objections?

**Comment by sheadawson** [comment]
Thanks, good suggestion :)
