### ISSUE TITLE
displayIf (display-logic) doesn't work when using validateIf

### ISSUE THREAD

**Issue by brasileric** [sheadawson/silverstripe-zenvalidator#29]
Hi,
I use this moduel in together with the display-logic module. But is I do this:

        $ProductSpecificationOtherField = TextField::create('ProductSpecificationOther', 'Other');
        $ProductSpecificationOtherField->validateIf('ProductSpecification')->isEqualTo('99999');
        $ProductSpecificationOtherField->displayIf("ProductSpecification")->isEqualTo('99999');

The field doesn't appear anymore when the value of ProductSpecification is 99999. If I use validateIf and displayIf separate from each other, they both work well.

**Comment by wernerkrauss** [comment]
Same here. That's annoying... Maybe because both have a method called `isEqualTo` ? Did you try another valdiation logic, e.g. isGreaterThan ? See https://github.com/sheadawson/silverstripe-zenvalidator#validation-logic-examples

**Comment by hesteric** [comment]
if I try other I have the same problem, like:

    $LifetimeField->validateIf('ProductPropertyID')->isGreaterThan(5);
        $LifetimeField->hideIf("ProductPropertyID")->isEqualTo(4);

**Comment by hailwood** [comment]
The theory here is correct,
The appropriate fix would be to prefix all js methods with e.g. ssZV so ssZVisEqualTo.
I can confirm that this works locally with the latest version of display logic.

**Comment by sheadawson** [comment]
That makes sense. If anyone has time to make a PR I'd be happy to merge. Otherwise I'll get to it as soon as I can :+1:

**Comment by hailwood** [comment]
Hey @sheadawson,

There was another issue that I ran into when doing this method wherein the field that was hidden by display logic - if it became visible again after the first time the form was submitted it was never validated which I could not solve.

**Comment by lekoala** [comment]
Since conditionnal validation is now backend only, is this issue still relevant?

As for the last comment of @hailwood , validation seems to happen fine if it's visible again after the first validation

**Comment by sheadawson** [comment]
Yeap, no longer relevant because we have removed frontend logic
