### ISSUE TITLE
Uncaught TypeError in JS

### ISSUE THREAD

**Issue by mi32dogs** [sheadawson/silverstripe-zenvalidator#33]
Hi Shea,

when i install this and try to use it in the cms i get the following two js errors
Uncaught TypeError: Cannot read property 'extend' of undefined
and 
Uncaught TypeError: undefined is not a function

is on a fairly clean install of SS3.1 and i like to use the client-side validation on a dataobject.
any tips on how i can make this work?

Thanks
Rob

**Comment by sheadawson** [comment]
Fixed the error, but client side validation in the CMS needs some work. I've updated the readme to suggest disabling parsley (clientside validation) when using zen validator in the cms. So you still get access to the advanced validation methods, but not the fast clientside validation error display
