### ISSUE TITLE
CheckBoxSetField Invalid Markup

### ISSUE THREAD

**Issue by charles-ritchie** [sheadawson/silverstripe-zenvalidator#36]
I have noticed that ZenValidator seems to cause invalid markup for the CheckBoxSetField.
E.g. two id's and two class attributes.
This is true for both the front and back end.
I have used

``` YAML
SSViewer:
  source_file_comments: true
```

to track down the offending template and it is definitely ZenValidator, as when I remove ZenValidator the problem is resolved. 

Here is an example of the invalid markup.

``` HTML
<div id="Sectors" class="field optionset checkboxset js-notice-sectors highlight-first" name="Sectors" class="optionset checkboxset js-notice-sectors highlight-first" id="GazetteNoticeForm_GazetteNoticeForm_Sectors">
    <label class="left">Notice sectors</label>
    <div class="middleColumn">
        <ul id="GazetteNoticeForm_GazetteNoticeForm_Sectors" class="optionset checkboxset js-notice-sectors highlight-first">


            <li class="odd val195">
                <input id="GazetteNoticeForm_GazetteNoticeForm_Sectors_195" class="checkbox" name="Sectors[195]" type="checkbox" value="195" />
                <label for="GazetteNoticeForm_GazetteNoticeForm_Sectors_195">Early childhood education (ECE)</label>
            </li> 

            <li class="even val196">
                <input id="GazetteNoticeForm_GazetteNoticeForm_Sectors_196" class="checkbox" name="Sectors[196]" type="checkbox" value="196" />
                <label for="GazetteNoticeForm_GazetteNoticeForm_Sectors_196">Primary and intermediate (Years 1-8)</label>
            </li> 

            <li class="odd val197">
                <input id="GazetteNoticeForm_GazetteNoticeForm_Sectors_197" class="checkbox" name="Sectors[197]" type="checkbox" value="197" />
                <label for="GazetteNoticeForm_GazetteNoticeForm_Sectors_197">Secondary</label>
            </li> 
        </ul>
    </div>
</div>
```

Running on vanilla SilverStripe.
If you need any more info, just ask and I will provide.
I presently don't have time to pursue this issue further, but will in the near future if you are too busy.

**Comment by lekoala** [comment]
Yes, the reason behind this is the custom template for CheckboxSetField. The problem should be just the same if you use Display Logic.
The problem is that the ul tag should not include the id and the class since SS 3.2. And we need to keep it to ensure compatibility with version 3.1.

I don't see any good way to solve this without breaking compatiblity with 3.1.

**Comment by charles-ritchie** [comment]
I also can't think of any way to get around this issue. Closing issue.
