### ISSUE TITLE
Remote validator works reverse?

### ISSUE THREAD

**Issue by brasileric** [sheadawson/silverstripe-zenvalidator#39]
Hi,

It looks like that the remote validator works reverse by default. I tried to change that by this:

    $validator->setConstraint('Username', Constraint_remote::create($this->Link('checkusername'),null,null,'default'));

But still httpError 200 gives a false validation and 400 gives a success. Or do I something wrong?

**Comment by lekoala** [comment]
Have you tried returning something as well in the body of the response? Typically, I return 1 or {success:true} for 200, and the error message as the body for 400.

**Comment by brasileric** [comment]
Hi lekoala,

Thanks for response.

The only thing what works wel for me is:

        public function checkusername($request){
        $username = $request->requestVar('Email');

        // check for existing user with same username
        if(Member::get()->filter('Email', $username)->count() > 0){
            return $this->getResponse()->setBody(false);
        }else{
            return $this->getResponse()->setBody(true);
        }
    }

And than a custom message in the validator itself. For me this is a good workaround.
By the way, I use SilverStripe 3.2.1.
