### ISSUE TITLE
If Zen validator is used in getCMSValidator() of a page the Settings tab throws an error

### ISSUE THREAD

**Issue by zarocknz** [sheadawson/silverstripe-zenvalidator#51]
Hi,

We discovered an issue where if a getCMSValidator() is specified for a page and in that the Zen validator is used to add constraints to a field then when we tried to go to the Settings tab for the page it throws the following error...

Argument 1 passed to ZenValidatorConstraint::setField() must be an instance of FormField, null given

Through much digging, discovered that the core Silverstripe cms/code/controllers/CMSMain.php gets the validator if the page has the method getCMSValidator defined and uses this for the settings page form rather than creating a new one (RequiredFields).

Then because some constraints were added to the fields on the main tab form in the getCMSValidator function Zen errors when trying to $constraint->setField($this->form->Fields()->dataFieldByName($fieldName)); because the field does not exist on the settings tab form.

I checked the RequiredFields validator code and it seems to avoid this issue by the way that it has been coded, and it also does not raise an error because it checks if the formField exists before setting the error message and valid = false.

Not 100% sure why CMSMain uses the validator defined in getCMSValidator for the settings tab, probably so if custom fields have been added there the dev can add a validation against them, and guess because of the way the RequiredFields is coded they have never hit the issue with the settings tab.

Anyway I figured out a simple adjustment to the Zen Validator which stops this error from happening, basically just checking the field exists on the form before adding the constraints to it. 

Will raise a pull request for this fix.

**Comment by sheadawson** [comment]
Fixed in #52
