### ISSUE TITLE
Custom constraint question

### ISSUE THREAD

**Issue by bjarman** [sheadawson/silverstripe-zenvalidator#53]
As a novis in creating custom validation constraints using zenvalidator I hope that someone can give me a hint on the best way of achieving the following.

Example:
Rank at least 3 of your favourite colors:
Red: 1st, 2nd, 3d or 4th
Green: 1st, 2nd, 3d or 4th
Blue: 1st, 2nd, 3d or 4th
Yellow: 1st, 2nd, 3d or 4th

Each color is represented by a radio button group where each radio button represents the rank from 1-4.
So, when the form is posted it would send for instance: red=3, green=2, yellow=3 etc.
I need to validate that the user has in fact rated no less than 1st,2nd and 3d out of all colors.

Is there a nifty way to create this type of validation constraint where there are several fields involved that need to be validated together?

**Comment by sheadawson** [comment]
Hmm I haven't had to do anything like this. One option might be to put all of those fields inside a FieldGroup, and apply a custom constraint to the FieldGroup. The constraint would check the values of the Fields contained in the FieldGroup.

**Comment by sheadawson** [comment]
Let me know how you get on. Closing for now.
