### ISSUE TITLE
[User Error] Uncaught Exception: There is a constraint for Title but this field does not exist. Maybe you should remove the constraint?

### ISSUE THREAD

**Issue by spekulatius** [sheadawson/silverstripe-zenvalidator#54]
Hello @sheadawson 

when using the Zenvalidator in the CMS for example to validate the title of a page, other tabs like 'Settings' start throwing this error:

    [User Error] Uncaught Exception: There is a constraint for Title but this field does not exist. Maybe you should remove the constraint?

The form really doesn't contain the title field, because the tab doesn't contain the field. Is this a known issue?

CMS/FW: 3.2.3, ZenValidator: 0.4.5

Cheers,
Peter

**Comment by sheadawson** [comment]
I see, I though we fixed this in #52 but yeap, we'll need to remove that user_error for it to work.
