### ISSUE TITLE
Exception when click save on page's Settings tab in CMS

### ISSUE THREAD

**Issue by zarocknz** [sheadawson/silverstripe-zenvalidator#55]
We're encountering an exception upon save when there is validation on fields on the Content tab of a page but we are on the Settings tab and clicking the save button after trying to update something there. This exception prevents saving changes on the Settings tab.

This is caused by the the following code around line 306 in ZenValidator.php...

`
if (!$field) {
    throw new Exception(
      "There is a constraint for $fieldName but this field does not exist. " .
      "Maybe you should remove the constraint?"
    );
}
`

Again this is because the fields on the Content screen do not exist in the posted form when on the Settings tab and the save is clicked. This is kind of related to issue #51 

The solution to this is to remove the throw of the exception and instead change the code below that to be like this...

`
if ($field && $field->validationApplies()) {
  foreach ($constraints as $constraint) {
    if (!$constraint->validate($data[$fieldName])) {
      $this->validationError($fieldName, $constraint->getMessage(), 'required');
      $valid = false;
    }
  }
}
`

I will raise a merge request to fix this. I'm hoping the throw of the exception is not really required for anything and was just a way to inform someone if there is a constraint for a missing field so can be removed.

Thanks,
DouG.

**Comment by zarocknz** [comment]
Sorry I see Peter has raised this too in #54 and a fix (continue) has already been done.

**Comment by zarocknz** [comment]
@sheadawson can you please do a new tagged release with the fix in it so composer will pull this down? Thanks.

**Comment by sheadawson** [comment]
Yes thanks for the reminder - https://github.com/sheadawson/silverstripe-zenvalidator/tree/0.5.1
