### ISSUE TITLE
Change to a vendor module

### ISSUE THREAD

**Issue by phptek** [sheadawson/silverstripe-zenvalidator#72]
Please consider modifying `composer.json` and making this package a `silverstripe-vendormodule` :-)

**Comment by lekoala** [comment]
done, but i'm not an expert on this since i mostly work with submodules installed in the root of my project. please confirm it works fine :)

**Comment by lekoala** [comment]
i fixed a couple of other things (requirements amongst others) it should be fine as far as i can tell
